### ISSUE TITLE
CAMB run to replicate output from TT emulator

### ISSUE THREAD

**Issue by karenperezsarmiento** [dpiras/cosmopower-jax#8]
Which CAMB settings replicate the output from the TT emulator in cosmopower-jax?

I tried running the following and the power spectra looks different.

```
cosmo_params = {
    "H0": 67.0,
    "As": 2.0989031673191437e-09,
    "ombh2": 0.02237,
    "omch2": 0.1200,
    "ns": 0.9649,
    "tau": 0.0544,
}

pars = camb.set_params(H0=cosmo_params["H0"],ombh2=cosmo_params["ombh2"], omch2=cosmo_params["omch2"], mnu=0.06, omk=0, tau=cosmo_params["tau"],  
                       As=cosmo_params["As"], ns=cosmo_params["ns"])
pars.set_for_lmax(2500, lens_potential_accuracy=1)
results = camb.get_results(pars)
powers =results.get_cmb_power_spectra(pars,CMB_unit="muK")
dls_tt = powers["total"][:,0]

cp_params = {'omega_b': [cosmo_params["ombh2"]/(cosmo_params["H0"]/100)**2],
                'omega_cdm': [cosmo_params["omch2"]/(cosmo_params["H0"]/100)**2],
                'h': [cosmo_params["H0"]/100],
                'tau_reio': [cosmo_params["tau"]],
                'n_s': [cosmo_params["ns"]],
                'ln10^{10}A_s': [np.log(10**10*cosmo_params["As"])],
                }

tt_emulator = CPJ(probe='cmb_tt')

tt_emulator_predictions = tt_emulator.predict(cp_params)
ell_range = tt_emulator.modes

plt.loglog((pars.TCMB*1e6)**2*ell_range*(ell_range+1)*tt_emulator_predictions/(2*np.pi),label="cosmopower")
plt.loglog(dls_tt,label="CAMB TT total")
plt.legend()


```
![ps_cpj_camb](https://github.com/user-attachments/assets/214b9cb9-9d7f-4fad-826c-094992a308cb)

**Comment by dpiras** [comment]
Hi @karenperezsarmiento, thank you for your interest in CosmoPower-JAX! 

The dataset used to train the models here is the same as in the original[ CosmoPower](https://github.com/alessiospuriomancini/cosmopower) paper, where you can find an [example](https://github.com/alessiospuriomancini/cosmopower/blob/cb323858f5567b61d3de71aadb452c95ef908984/notebooks/getting_started_notebooks/getting_started_with_cosmopower_NN.ipynb) of a spectrum generation with Class. Your way of generating spectra with CAMB seems correct; however, please note that we did not include neutrinos (`mnu=0`), and most things were left as default.

There are however a couple of other issues. First, please note that our `omega_b` and `omega_cdm` are the same as those that go as input into CAMB, so they are already rescaled by `h**2`. Also, note that we discard the first two `ell` values, so 
`dls_tt = powers["total"][2:,0]`.

With these changes, I'm able to obtain a plot like the one attached. I'm closing the issue, but feel free to reopen it in case something is not clear, or you need further help.

![image](https://github.com/user-attachments/assets/af6d1bee-249e-4091-8308-c8cbfeab36c4)
